name: mobile_project
description: "A new Flutter project."
publish_to: 'none' # Отключаем публикацию на pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Поддержка Dart SDK версий от 3.0.0 до 4.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Иконки Cupertino для iOS
  http: ^1.3.0 # HTTP-запросы
  audioplayers: ^6.4.0 # Воспроизведение звуков
  connectivity_plus: ^6.1.3 # Проверка подключения к интернету
  hive: ^2.2.3 # Локальное хранилище данных
  hive_flutter: ^1.1.0 # Flutter-интеграция для Hive
  flutter_tts: ^4.2.2 # Текстовый синтез
  url_launcher: ^6.3.1 # Открытие ссылок
  cached_network_image: ^3.4.1 # Загрузка и кэширование изображений
  share_plus: ^10.1.4 # Деление результатов
  animated_splash_screen: ^1.3.0 # Анимированный экран загрузки
  page_transition: ^2.2.1 # Анимированные переходы между экранами
  confetti: ^0.8.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_bloc: ^9.1.0
  lottie: ^3.3.1
  webview_flutter: ^4.10.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  flutter_localizations:
    sdk: flutter
  percent_indicator: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Статический анализ кода

flutter:
  uses-material-design: true # Использование Material Design иконок
  assets:
    - assets/sounds/ # Папка для звуковых файлов
    - assets/images/success.jpg
    - assets/images/good.jpg
    - assets/images/try_again.jpg